### ISSUE TITLE
Image metadata is ignored (IJKToRASDirections, view order issue - numpy array of volume node [:, 1, :] corresponds to red view in MRI, but [:, :, 1] in CT)

### ISSUE THREAD

**Issue by dzenanz** [bingogome/samm#13]
I have some images with non-identity metadata (e.g. “CBCT-MR Head” from Slicer's Sample Data module). When clicked, fiducial points are placed in a wrong location, preventing proper operation.

**Comment by bingogome** [comment]
That's interesting. We did notice some problems with the function GetRASToIJKMatrix(). It could be a rounding issue of the integers. Will need to investigate more.

**Comment by bingogome** [comment]
Currently the segmentation prompts are assumed to be dropped on Red view, and the IJKToRASDirections needs to look similar to [[0,0,1],[-1,0,0],[0,-1,0]] (Basically MRI images). This works on my MRI dataset and the MRHead sample data.  

I can't seem to find an elegant way to solve this at the moment. For CT images, I had to do both: 1. disable processPromptPointsSync() in LogicSamm.py and 2. observe which view (Red, Green or Yellow) is the axis that slices were computed along. I did this to play around and got some segmentation from CTs. Both are related to indexing of the array, which I hard-coded. (admittedly, very embarrassing ...). I will keep looking into it, but if anyone wants to give some advice, I'd love to implement them.

**Comment by lassoan** [comment]
I would recommend to implement this as a Segment Editor effect. You then get a warning button if the slice view is not aligned with the segmentation and you can snap the view to the image grid by a single click. In the effect it would be enough to just detect the misalignment and display a warning (and ask the user to align the views).

"Level tracing" effect has the same limitation that it works only in axis-aligned slices. It does not warn the user if the view is misaligned (not nice, should be fixed) but you can use it as an example of how to get the click position in voxel (IJK) coordinates and how to determine the image plane of the current slice view:

https://github.com/Slicer/Slicer/blob/main/Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorLevelTracingEffect.py

**Comment by Guhanxue** [comment]
yeah, meet same issue here. When clicked, fiducial points are placed in a wrong location...

**Comment by bingogome** [comment]
Thanks for the suggestions. 

I wonder if there is a way to get the corresponding view order of the volume node. In the current implementation, Slicer transmits the images (slices) from the volume node's numpy array, say [:,1,:], for red view. However, it changes if the IJKToRASDirections are not in the same order (misalignment was actually not an issue, see next paragraph). For example, for CTs, the red view is [1, :, :] (or [:, :, 1], I do not remember exactly from my tests). With the correct order, I can fix this for good. 

We did handle IJKToRASDirections for promptPointsSync, where if you slide up and down, the prompts will go with the slice. This feature became a bug, unfortunately, for those images with the order of view not aligning with MRI ([[0,0,1],[-1,0,0],[0,-1,0]], or anything closer to it. In fact, our test data is misaligned slightly, but the prompts worked perfectly well.)

**Comment by Guhanxue** [comment]
Hi, thanks a lot for your quick update! I tried a CT example in 3D slicer  and the prompt do looks fine. But when i this MRI example, the set point will be far away with my placement. Is it the because of the reaon you explain here? 
<img width="222" alt="image" src="https://user-images.githubusercontent.com/39239103/231920507-6a20c305-2950-43e8-b48c-9f33e6b67a15.png">

**Comment by lassoan** [comment]
I would recommend using the same logic for getting the image axis and IJK position as it is done in the Levél tracing effect. That works well when when view axes are aligned with any of the image axes in any direction. It works with MRBrainTumor2 data set, too. For oblique cases your can display a warning (and the user can align the view by a single click).

**Comment by bingogome** [comment]
8ed1ed60d7a49b75048b8b19093e59a5ba959c3c Issue resolved with a not-so-elegant way. Tested on MRHead and CTChest. But I will keep this issue open, will need to come back to take a look at @lassoan 's suggestions. Hard to find time. @dzenanz Is CBCT-MR data DZ-MR? I tried DZ-MR, seems to work now. Please report if it doesn't work for you. @Guhanxue This dataset is now working for me. Could you test it out?

**Comment by dzenanz** [comment]
Yes, CBCT-MR == DZ-MR. Unfortunately, this still does not work for me, as of 9421c5901090f1ce6e9f260808d98f26dafd1560. Clicking on the eye in the red slice was interpreted as a point somewhere between the eyes in the yellow slice:
<img width="1363" alt="Screenshot 2023-04-17 10 36 21" src="https://user-images.githubusercontent.com/1792121/232519510-fee44be8-495c-4602-b47e-e3dcb248421c.png">

Then yellow slice somewhat works. There is this error too:
```log
Traceback (most recent call last):
  File "M:\Ethicon\samm\samm\SammBase\SammBaseLib\LogicSamm.py", line 363, in processPromptPointsSync
    ras = self._volumeIjkToRas.MultiplyPoint([temp[0],temp[1],curslc, 1])
UnboundLocalError: local variable 'curslc' referenced before assignment
```

**Comment by dzenanz** [comment]
After finishing the first slice, the program stopped working. There is this stream of errors in the server console:
```log
All images have been processed.
ERROR:root:Traceback (most recent call last):
  File "sam_server.py", line 261, in main
    srv.infer_image( \
  File "sam_server.py", line 179, in infer_image
    memmap = np.memmap(self.workspace + '/mask.memmap', dtype='bool', mode='w+', shape=self.masks[0].shape)
  File "m:\Ethicon\env\lib\site-packages\numpy\core\memmap.py", line 228, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
OSError: [Errno 22] Invalid argument: 'M:\\Ethicon\\samm\\samm-python-terminal\\samm-workspace/mask.memmap'
```
Here is what the first slice looked like:
<img width="1360" alt="Screenshot 2023-04-17 10 45 46" src="https://user-images.githubusercontent.com/1792121/232521948-9cd6dc2b-14ba-4bf9-bdb7-34e747888d06.png">

**Comment by bingogome** [comment]
This issue should now be fixed with changes in 5b63c7dfa120c39066215fb766f8b246be3e2414. I removed the fiducial synchronization and also used both IJKToRASDirections and XYToRAS to solve the problem with view mismatch, without reformatting the data.
